### PR TITLE
Babelua added

### PR DESCRIPTION
**Pull request by SiENcE**
Babelua extension for Visual Studio added to IDEs

### CODE REVIEW

**Comment by JanWerder** [comment]
Did you get to work? I tried it for myself, but didn't get it running

**Comment by SiENcE** [comment]
What do you mean? Follow the install instructions (install and only the FIRST start as Admin) and all should be good.

Whats the problem :) ?

**Comment by JanWerder** [comment]
What is the lua script path? Do I really need to have the original Lua? Where do I select it to run Love? I tried to make a new Project with it and it tried to create a Folder in Program Files, which it wasn't allowed to do. 😕

**Comment by JanWerder** [comment]
Mhm, I still haven't added this because I think the documentation of Babellua is still not good enough. I know some members of the community have gotten this to work and I don't want to play the articficial quality gate here, but I seriously doubt that this link is helpful without proper context. Also codeplex is shutting down, so we would need a new link anyways

**Pull request closed without merging**
