### PR TITLE
Add Game State Management section, along with new library

### PR DESCRIPTION
**Pull request by thenerdie**
I created a game state lib recently that needs to be added: A ridiculously easy to use game state management library written in Lua, for the LOVE2D framework.

There was no proper section for the library, so I made a new one.

### CODE REVIEW

**Comment by rm-code** [comment]
@thenerdie The "Helper Libraries" section contains a few gamestate libraries. They could be added to your new section as well.

**Comment by JanWerder** [comment]
I would like to add it, but the documentation is lacking and the category "Helper Libraries" would be better suited. If you could improve on these two points, I would happily accept your PR. As it stands I will leave this PR open for a couple of days.

**Comment by thenerdie** [comment]
@JanWerder i did the thing

**Comment by JanWerder** [comment]
Thanks for doing the thing

**Pull request merged**
