### PR TITLE
add breezefield library to Physics category

### PR DESCRIPTION
**Pull request by HDictus**
Breezefield is a simple wrapper of love.physics module, inspired by Windfield, but more minimalistic and therefore more transparent, simpler to use, modify, read, and fully understand. 
I personally find using this library to be preferable to the one that inspired it - windfield, and I believe it to be a solid alternative for anyone - especially for prototyping.
forum post: https://love2d.org/forums/viewtopic.php?f=5&t=86113&p=224718#p224718
Cheers!

### CODE REVIEW

**Comment by rm-code** [comment]
@HDictus I just restarted the build. Should be done in a few minutes.

**Comment by rm-code** [comment]
@HDictus awesome-love2d uses an alphanumeric order for the listed libraries. So breezefield needs to moved up a few lines in the list 🙂

**Comment by JanWerder** [comment]
What a shame that Moan.lua is gone, but thanks for your commit! 😄

**Comment by HDictus** [comment]
Thanks!

**Pull request merged**
