### PR TITLE
New category - Tooling. New Entry for Tooling - project flirt (engine versions manager)

### PR DESCRIPTION
**Pull request by zugzug90**
New category - Tooling. New Entry for Tooling - project flirt (engine versions manager)

Flirt is a small script for picking the appropriate version of LOVE to use for any given LOVE game. To run flirt, you'll need a Unix-like environment with the following commands:

    lua 5.1
    unzip
    which
    test
    mkdir

This means no Windows, sorry.

### CODE REVIEW

**Comment by rm-code** [comment]
@zugzug90 @JanWerder I think this would fit in the "Utilites" section (seeing that we already feature love-pe there). Maybe we should just change the description for that section from `Non-Game specific Library bundles, that provide reuseable functions` to `Non-Game specific libraries and tools` or something along those lines?

**Comment by JanWerder** [comment]
@rm-code Yes I agree, a new section would be too much.
@zugzug90 Can you change your PR?

**Comment by zugzug90** [comment]
@JanWerder 
> @zugzug90 Can you change your PR?
Sure, not a problem.
Btw, could you please help me to understand why `ci-build` failed for my `PR`?

**Comment by JanWerder** [comment]
Sure, the CI has failed because a community member has renamed himself again. I will fix that after your PR :)

**Comment by rm-code** [comment]
@JanWerder I went ahead and fixed the URLs yesterday evening... after seeing the failed build. Forgot to mention it here.

**Comment by zugzug90** [comment]
@rm-code @JanWerder Hi, I've updated my `PR` you can check it out.

**Comment by JanWerder** [comment]
Looks fine to me, thanks!

**Pull request merged**
