### PR TITLE
Added: MeowUI

### PR DESCRIPTION
**Pull request by Tourahi**
This might be the first lib here thats written in MoonScript. I had so much fun making it and i hope it will be useful for other devs.

### CODE REVIEW

**Comment by alejandro-alzate** [comment]
You're pretty much the first sharing a moonscript library here, I'm looking forward to this evolve.

Bc mooonscript is a cool oop language and (although as a mess) compiles back to pure lua.

**Comment by MikuAuahDark** [comment]
I suggest adding pre-compiled Lua files for ease of installation.

**Comment by alejandro-alzate** [comment]
> I suggest adding pre-compiled Lua files for ease of user-end installation who doesn't use MoonScript.

I suggest the use of a build dir for the lua files

**Comment by alejandro-alzate** [comment]
Also fun fact i think the moonscript has a runtime compiler for moon files written on pure lua, so if you don't wanna deal with a bunch of obfuwcated lua files, you could bundle the interpreter with your library so it compiles on the fly and interfaces with pure lua like nothing happened.

Making the user both agnostic and oblivious of the behind the scenes.

**Comment by MikuAuahDark** [comment]
On 2nd thought, let's make "precompiled Lua files" a requirement. It's important that a library is "easy to install" instead of having user bundling MoonScript compiler or using MoonScript.

Let me know once you done that so I can merge this.

**Comment by Tourahi** [comment]
Done, MeowUI release 0.1 is out ヾ(＾▽＾)ﾉ.
You will find the pre-compiled version attached to the release and also there is a new branch [master-lua](https://github.com/MoonGameLab/MeowUI/tree/master-lua). This way the user can clone from it directly without the need of compiling.

**Comment by alejandro-alzate** [comment]
> Let me know once you done that so I can merge this.

> Done, MeowUI release 0.1 is out ヾ(＾▽＾)ﾉ.

Just pinging for good measure. @MikuAuahDark

**Comment by alejandro-alzate** [comment]
Hooray!

**Pull request merged**
