### PR TITLE
Added Zed to editors list

### PR DESCRIPTION
**Pull request by alejandro-alzate**
Hopefully this goes through the linter first try

### CODE REVIEW

**Comment by alejandro-alzate** [comment]
Alright first try!
:)

**Comment by MikuAuahDark** [comment]
Are there specific setup for Lua and LOVE integration? If so, it would be worth to link them too beside Zed.

**Comment by alejandro-alzate** [comment]
> Are there specific setup for Lua and LOVE integration? If so, it would be worth to link them too beside Zed (look on existing entires for an example).

When you open a lua file the first time it will ask you if you wanna install the luals server.
You click install and that's pretty much all of it for the lua side of things, it's such a pleasure to work with zed's intellisense.

Now for love specific syntax I'm cooking typing hinting files for zed
github.com/alejandro-alzate/love2z
But I'm still working on it, shall i add it?

**Comment by alejandro-alzate** [comment]
love2z it's almost there I'm fixing the edge-cases here and there but the functions predictions are basically there, and i tracked down the thing that makes lua just work on zed:
https://github.com/zed-industries/zed/tree/main/extensions/lua

**Comment by MikuAuahDark** [comment]
For the LOVE specific type hints, consider using https://github.com/love2d-community/love-api instead of hand-writing it. That being said, quick look on the file, the type hinting syntax looks like similar so Sumneko/LuaLS, so you may able to use https://github.com/LuaCATS/love2d instead.

Do you want me to merge this right now or do you also want to finish then add love2dz to the list?

**Comment by alejandro-alzate** [comment]
I actually started rawdogging from the wiki copying it by hand and after love.audio I started thinking hell no this is painful and grabbed a love-api copy (bc in my madness i remember it's existence).

Now said that, god damn don't tell me I lost an entire week writing a parser :(

For now you can do either (im inclined to add it nontheless) the funtions and enums are there but object types require a tiny bit of manual intervetion.

I'll take look to that repo to dissapoint me with myself.

Also side note is love2z (swap the `d` with the `z`) not that im bothered by the typo though.

Who knows maybe I learn rust and make a love2d specific thing for zed that becomes a must have...

**Comment by alejandro-alzate** [comment]
Yeah it looks very similar, I gotta beat them with something zed-specific.

Guess ~~we doing circles~~ I'm learning rust now.

**Pull request merged**
