### PR TITLE
Add extensions for Brackets

### PR DESCRIPTION
**Pull request by instilledbee**
Added entries for the Brackets editor and some extensions:
* Lua Syntax Highlighter
* LÖVE Hints for Brackets
* Run LÖVE

### CODE REVIEW

**Comment by rm-code** [comment]
@instilledbee There is a fullstop that could / should be removed at the end of the Run LÖVE description :)

**Comment by rm-code** [comment]
Also looks like the url for brackets should be changed to http://brackets.io/

**Comment by instilledbee** [comment]
@rm-code Thanks. I've addressed those in the latest commit. :)

**Comment by JanWerder** [comment]
Thanks for the contribution! 😄

**Comment by rm-code** [comment]
🎉

**Pull request merged**
