### PR TITLE
Optikon Level Designer

### PR DESCRIPTION
**Pull request by optikon-lvl**
## Utilities

* [Optikon Level Designer](https://optikon.co.uk) - A simple and intuitive WYSIWYG visual level designer for LÖVE that does all the basic Lua coding for you

### CODE REVIEW

**Comment by JanWerder** [comment]
Mhm, I the pull request seems broken in what it wants to add.
I think Optikon would better belong in the IDE category.
I'm leaving this PR open for a few days for others to comment on that.
If no one responds I will add it to the IDE category with the URL to the main site instead of a direct download URL.

**Comment by optikon-lvl** [comment]
Thank you Jan

**Comment by optikon-lvl** [comment]
Thank you Jan; Optikon is a simple level editor. It doesn't qualify as an IDE, it's a tool, and so we have proposed it is added to the 'utilities' category.

**Comment by JanWerder** [comment]
Ok, thanks. I'll add it, but close this PR.

**Pull request closed without merging**
