### PR TITLE
Added a fantastic tutorial link.

### PR DESCRIPTION
**Pull request by iiviigames**
The link is the blog written by the creator of the LOVE made BYTEPATH. It reads more like a book, with actual lessons, chapters, and even challenges for readers to try to tackle on their own before getting the answers. The fact that this tutorial is free is unreal, because it obviously took an inordinate amount of time to create. I learned more from this single resource than anything else on the whole list! That's why I thought I'd add it. Hope all is well!

### CODE REVIEW

**Comment by JanWerder** [comment]
Well, thanks for submitting, but the link to the blog of a327ex was just removed from the list with https://github.com/love2d-community/awesome-love2d/issues/212.
I think we'll stay with that decision for now.

**Comment by iiviigames** [comment]
I'm totally confused? Why is it removed? It's a tutorial about making a game with Love2D?

**Comment by iiviigames** [comment]
I don't know what this is about - but the link I provided is literally just 10 sections of lua programming and I think what you're saying is that this same user said something that bothered someone in his blog - but that's completely irrelevant. It's content that has nothing to do with whatever that is.

**Comment by huhwhatthe** [comment]
It has to do with it since it's on the same blog... but, no, I'm not sure what's Lua to do with Hitler, either... maybe ask a327ex...

**Comment by magnusviri** [comment]
That blog post uses a controversial video game as an example. I didn't think the post endorsed the game. I couldn't find any instance of the word "Hitler" on the blog. I looked in archive.org at the blog post titles and it all seemed to focus on philosophy or video games.

**Comment by slime73** [comment]
The author of the tutorial and blog posts has been using love for around a decade or more. During that time he's espoused more and more bigotry on multiple platforms (including but not limited to his github) without indication that he's learned to be a better person and made amends. That blog post mentioned in the other issue is just one part of a much larger pattern with him.

I will not be part of any form of tacit support of him, including support via amplifying his work or brand.

**Pull request closed without merging**
